version: '3.8'

services:
  django_app:
    build: .
    env_file:
      -  .env
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn main_app.wsgi:application --bind 0.0.0.0:8000 "
    volumes:
      - static_vol:/app/static
      - media_vol:/app/media
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static_vol:/app/static
      - media_vol:/app/media
    ports:
      - "80:80"
    depends_on:
      - django_app
      
volumes:
  static_vol:
  media_vol:
